# Generated by Django 2.0.7 on 2018-07-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('Email', models.EmailField(max_length=254)),
                ('Subject', models.CharField(max_length=120)),
                ('Message', models.TextField()),
            ],
        ),
    ]
